### ISSUE TITLE
Issue : no .csv files output & warnings

### ISSUE THREAD

**Issue by RossezA** [polarityjam/polarityjam#138]
Dear PolarityJam developers and administrators,

I am currently working on collective migration and related behaviours in epithelial cells monolayers  and thanks to your promising tool I might be able to extract features and quantify the microscopic imaging I have.

However I encountered some issues while following your install tutorial, I used the following commands as you wrote on your website:
conda create -y -n polarityjam python=3.8
conda activate polarityjam
pip install polarityjam
(with Anaconda)

Yet afterwards when running PolarityJam with your default .yml parameter file 
or one changed to better the results, I got two problems :
-First one is the fact that it seems to not find a defined mask in the files and loops until it decides to use a simple thresholding to proceed; At the end I also get "IndexError: list index out of range" 
-Second one I do not get .csv files as mentioned in the introduction to PolarityJam but only the visualizations as .png/.svg . Thus I am unable to perform a quantification of the features and use the web-app afterwards.

I put below this message one of the test run results and examples of visualizations we obtained as well as the logs showing the warnings/errors.
[Warnings_during_process.txt](https://github.com/polarityjam/polarityjam/files/14421683/Warnings_during_process.txt)
![40X_epithelial_cells_segmentation](https://github.com/polarityjam/polarityjam/assets/121632854/e30b872b-d88e-4aa1-8175-03fad25a2a8b)

![63Xoil_marked_epithelial_cells_segmentation](https://github.com/polarityjam/polarityjam/assets/121632854/3fcebd81-778d-48fc-8331-7237d6d60591)

**Comment by jpalbrecht** [comment]
Hi again.
Thank you for the detailed feedback. This helped me understanding where an error might be. 
So there seemes to be a problem with calculating the masks that divide cells in two or four parts, respectively - at least for certain cells. This causes a downstream error when trying to plot these. The reason you are not receiving a `.csv` is that the program breakes before the code is reached to save this file to disk.
So what you can do for now is to disable this plot: `plot_sc_partitions` by setting the value to False in the configuration file until we found the problem. That should ensure the program finishes and the csv. file is obtained. 

Are you willing to share that particular file with me that produced this error? I would like to use this and your configuration to detect why our cell partition algorithm fails. 

Let me know if that helped you in producing the csv file.

**Comment by RossezA** [comment]
Absolutely, here are the parameter files I used to study epithelial cells, as well as the .tif image with 2 channels (nuclei, membrane marking) : 
-cellpose.yml (calibrated for our cells on 1462x1462 images) 
```
# SegmentationParameter
path: cellpose.CellposeSegmenter
channel_cell_segmentation: "" # always uses the noted channel for segmentation of cells. leave empty for default.
channel_nuclei_segmentation: "" # always uses the noted channel for segmentation of nuclei. leave empty for default.
manually_annotated_mask: "" # in case a manually annotated cellpose mask exists specify suffix here
store_segmentation: True
use_given_mask: True
model_type: "cyto2" # "cyto", "cyto2", "custom"
model_type_nucleus: "nuclei" # "custom"
model_path: ""
estimated_cell_diameter: 120 # estimated cell diameter in pixels ; default is 100
estimated_nucleus_diameter: 80 # estimated nuclei diameter in pixels ; default is 30
flow_threshold: 0.8 # default cellpose value 0.4
cellprob_threshold: -0.8 # default cellpose value 0.0
use_gpu: True
```

-parameters_calibrated.yml (calibrated for our cells on 1462x1462 images)
```
############ Please read carefully ############

# ImageParameters
channel_junction: 1
channel_nucleus: 0
channel_organelle: -1
channel_expression_marker: -1 # -1 means no expression marker
pixel_to_micron_ratio: 1.0

# RuntimeParameter
min_cell_size: 400 # minimum area of cell in pixel^2, will be removed otherwise
min_nucleus_size: 300 # minimum area of nucleus in pixel^2, will be removed otherwise
min_organelle_size: 200 # minimum area of organelle in pixel^2, will be removed otherwise
extract_group_features: True
membrane_thickness: 4
junction_threshold: -1 # -1 means no manual thresholding, but otsu thresholding
feature_of_interest: "cell_eccentricity"
dp_epsilon: 5
cue_direction: 180 # should be provided in degrees and take values between 0 and 359 ; I put 180 to have from right to left as usual
connection_graph: True
segmentation_algorithm: "CellposeSegmenter" # "CellposeSegmenter", "SamSegmenter", "DeepCellSegmenter", "MicrosamSegmenter"
remove_small_objects_size: 30 # in pixels, put to 0 to disable
clear_border: False
keyfile_condition_cols: ["short_name"] # only needed if run_key option is used
save_sc_image: True

# PlotParameter
plot_junctions: True
plot_polarity: True
plot_elongation: True
plot_circularity: True
plot_marker: True
plot_ratio_method: False #Disabled
plot_shape_orientation: True
plot_foi: True
plot_processed_masks: True
plot_sc_image: True
plot_sc_partitions: True
show_statistics: True 
show_polarity_angles: True
show_graphics_axis: True
show_scalebar: True
length_scalebar_microns: 25.0
outline_width: 2 
graphics_output_format: ["png"] # 'png', 'pdf', 'svg'
dpi: 300
graphics_width: 5 # figure width in inches
graphics_height: 5 # figure height in inches
length_unit: "pixel" # "microns"
fontsize_text_annotations: 5
font_color: "r"
marker_size: 2
alpha: 0.7
alpha_cell_outline: 0.5

```

As for the input.tif I used, as GitHub does not accept .TIF I saved each channel into a .PNG to avoid losing too much data; you can reconstruct the .TIF in 2 channels using Image>Stacks>Images to Stack in Fiji/ImageJ and then saving it back into a .TIF (Hopefully this works, otherwise I'll try to find a way to give you the original .TIF)
![Epithelial_cells_2_channels_63Xoil_membrane](https://github.com/polarityjam/polarityjam/assets/121632854/ce37c2af-c02f-4803-a84f-b792baf2cec1)
![Epithelial_cells_2_channels_63Xoil_nuclei](https://github.com/polarityjam/polarityjam/assets/121632854/4a07ebb0-145f-4891-a6cf-dfa6f62ceea2)


In the meantime I will try out a new run of polarityjam while disabling `plot_sc_partitions`

Thanks again !

**Comment by RossezA** [comment]
Hi again @jpalbrecht ,

I got much better results after disabling `plot_sc_partitions` : I now have a .csv file containing the data I needed !
Nonetheless I still get the same loop of warnings as previously, and even after disabling `plot_sc_image` and/or `plot_processed_masks`.
However this does not seem to break the code as the plot_sc_partitions argument did.

Therefore thank you a lot for all the help you brought !
I will try out the PolarityJam-App and come back on the other GitHub if I get an issue in the analysis of my data.

I am not closing this issue as I don't know if you want to search more about the loop of warnings; if you need more info about it or want me to test eventual fixes you find, I'd be happy to do so !

**Comment by jpalbrecht** [comment]
the description pointed to the cell partition bug. Should not happen again.
