### ISSUE TITLE
Suggestion : why not use Cellpose3 for segmentation ?

### ISSUE THREAD

**Issue by RossezA** [polarityjam/polarityjam#141]
Hello dear PolarityJaM administrators and developers,

As I did not find somewhere to post that except in the "Issues", I am writing here my suggestion. Hopefully this won't disturb you in your work.

I have been using PolarityJaM (PJM) for several weeks now and I saw that it could load directly previous segmentation files from Cellpose.
In the case of PJM here it is Cellpose1 but I was wondering if Cellpose3 segmentation files would work, this would allow to get better segmentation results since their models really improved a lot these past years.

Turns out PJM can read and process the rest of its analysis from these segmentation files (.npy) ! I henceforth wondered if it was possible to implement that in PJM directly instead of switching manually between cellpose and polarityjam environments ?

Of course I haven't digged in the code that makes up PJM so I don't really know if what I'm suggesting is really feasible or not.
In case you are interested I uploaded the image I used (apical part of an Epithelial cells stack, deconvoluted using Richardson-Lucy algorithm) as well as links to download my two different segmentation files (.npy not accepted by GitHub otherwise).
![63X_Epithelialcells_DeconvolutedRLTV](https://github.com/polarityjam/polarityjam/assets/121632854/ccb41f72-b68f-4372-a56a-2ec9a0772b59)

https://drive.google.com/uc?export=download&id=1QoBqXKNgTkWYlSn9wJQaLDFUbclgQhH0 (Segmentation file of PolarityJaM)

https://drive.google.com/uc?export=download&id=1gYsVeUxZh4jctAsOhEuktCuQt0xpj-Dz (Segmentation file of Cellpose3)

**Comment by jpalbrecht** [comment]
Dear @RossezA, please never feel like you distrub our work. Thank you for your suggestion. 

We will keep the issue open and hope we will soon be able to upgrade to cellpose3.

Thank you also for your segmentation files. They will serve as great reference.

**Comment by jpalbrecht** [comment]
we connect this issue with issue #122. An update to the latest cellpose version will be in our next release.

**Comment by jpalbrecht** [comment]
cellpose 3 is now supported by default
