### ISSUE TITLE
provide warning in case Moran's I computation fails

### ISSUE THREAD

**Issue by wgiese** [polarityjam/polarityjam#22]
In case of segmenting single isolated cells in an image the Moran's I computation would through an error. Same if the user sets a high or too low cell diameter. So the response should be a warning that Moran's I, because of too few or only isolated cells. Also suggest the user to try a different segmentation parameters or segmentation model.

morans_i = run_morans(rag, self.params.feature_of_interest)
  File "...\polarityjam\src\polarityjam\compute\moran.py", line 488, in run_morans
    weights = W.from_networkx(rag)
  File "...\polarityjam\src\polarityjam\model\weights.py", line 238, in from_networkx
    sparse_matrix = [nx.to](http://nx.to/)_scipy_sparse_matrix(graph)
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges

**Comment by jpalbrecht** [comment]
happens when: 
- segmentation is bad -> cells are disconneted -> improve segmentation warning instead Moran fail
- isolated cells images as input (e.g. yeast cells or smiliar)

Switch off neighborhood analysis?
