### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by jpalbrecht** [polarityjam/polarityjam#33]
- [x] example parameter file
- [x]  example run commands (all three cases) + example key file
- [x] new pip install procedure
- [x] ";" missing in a notebook
- [x]  add eprivacy label
- [x] add cell X,Y axis mess up
- [x] Web page scaffold
- [x] web installation update
- [x] plots as jb notebook
- [x] renew plots in documentation, rebase on master first (e.g. rerun the notebooks)

**Comment by wgiese** [comment]
update installation of app to 
"git clone https://github.com/polarityjam/polarityjam-app.git # via git or download via browser

cd polarityjam-app
conda env create -f polarityjam-app.yml
conda activate polarityjam-app
Rscript app/app.R"

**Comment by jpalbrecht** [comment]
todo: make a polarityjam.yml environment file

**Comment by jpalbrecht** [comment]
add cue intenstiy plots in documentation
