### ISSUE TITLE
ratio method based on cue direction

### ISSUE THREAD

**Issue by jpalbrecht** [polarityjam/polarityjam#39]
user should define a cue direction (e.g. flow) as angle in degree - 0° = flow from left to right.
In two  axes,45° deg and -45° deg from the centroid of each cell based on the cue angle there should be calculated the polarity of the membrane protein (e.g. junction intensity) such that:

two ratios can be added as features:
- (left vs. right)-ratio (absolut value?)
- (top + bottom vs. left + right)-ratio (absolut value?)

(left, right, top, bottom refers to each of the quarters spanned from the two axes)

**Comment by wgiese** [comment]
I would only provide the ratio, since the intensity values are arbitrary units and the absolute values not comparable.
