### ISSUE TITLE
partition_single_cell_mask produces rare error

### ISSUE THREAD

**Issue by wgiese** [polarityjam/polarityjam#83]
In rare occasions partition_single_cell_mask produces an error

assert len(masks) == num_partitions, "Number of partitions(%s) does not match the number of masks (%s)." % (
AssertionError: Number of partitions(4) does not match the number of masks (1)

--> find good test case
--> print warning instead of error

**Comment by jpalbrecht** [comment]
both, warning and fix based on test case have been implemented
